export declare enum JenisNotifikasi {
    RETENSI_AKTIF_BERAKHIR = "RETENSI_AKTIF_BERAKHIR",
    RETENSI_INAKTIF_BERAKHIR = "RETENSI_INAKTIF_BERAKHIR",
    USUL_MUSNAH_BARU = "USUL_MUSNAH_BARU",
    USUL_MUSNAH_DISETUJUI = "USUL_MUSNAH_DISETUJUI",
    USUL_MUSNAH_DITOLAK = "USUL_MUSNAH_DITOLAK",
    PERPANJANGAN_DISETUJUI = "PERPANJANGAN_DISETUJUI",
    PERPANJANGAN_DITOLAK = "PERPANJANGAN_DITOLAK",
    VERIFIKASI_SETUM_DIBUTUHKAN = "VERIFIKASI_SETUM_DIBUTUHKAN"
}
//# sourceMappingURL=jenis-notifikasi.enum.d.ts.map